# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET
permissions:
  contents: read

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetches full history including all branches
  
    - name: "Install .NET"
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: "Install SonarScanner"
      run: dotnet tool install --global dotnet-sonarscanner

    - name: "Install dotnet-coverage" 
      run: dotnet tool install --global dotnet-coverage

    - name: "Configure SonarCloud"
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: dotnet sonarscanner begin /o:"doormalena" /k:"NLBE-Bot" /d:sonar.token=$SONAR_TOKEN /d:sonar.cs.vscoveragexml.reportsPaths=coverage.xml /d:sonar.coverage.exclusions=*.Tests/**/*

    - name: "Restore dependencies"
      run: dotnet restore

    - name: "Build"
      run: dotnet build --no-restore --no-incremental

    - name: "Test"
      run: dotnet-coverage collect "dotnet test --no-build" -f xml -o "coverage.xml"

    - name: "Publish SonarCloud results"
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: dotnet sonarscanner end /d:sonar.token=$SONAR_TOKEN
